package com.bibernate.hoverla.annotations;

public @interface GeneratedValue {

  GenerationType value();
  /**
   * The name of the generator to use. {@link SequenceGenerator#name()} should be specified.
   */
  String generator() default "";

  enum GenerationType {
    /**
     * Indicates that the column should be generated by the database primary key column.
     */
    IDENTITY,

    /**
     * Indicates that the column should be generated by using a database sequence.
     * If the current type is used, then specify {@link GeneratedValue#generator()} name.
     */
    SEQUENCE
  }

}
