package com.bibernate.hoverla.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation used to specify that the annotated field's value will be automatically generated by an identity column in the database.
 * <p>
 * This annotation should be applied to fields in entity classes to indicate that their values will be automatically generated by an identity column in the database.
 * </p>
 * <p>
 * Example usage:
 * <pre>{@code
 * @Entity
 * public class Product {
 *     @Id
 *     @IdentityGeneratedValue
 *     private Long id;
 *
 *     private String name;
 *
 *     private double price;
 *
 *     // Constructors, getters, setters, etc.
 * }
 * }</pre>
 * </p>
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface IdentityGeneratedValue {

}
