package com.bibernate.hoverla.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Indicates that the annotated field's value will be generated by a database sequence.
 * <p>
 * Example usage:
 * <pre>{@code
 * @Entity
 * public class Product {
 *
 *     @Id
 *     @SequenceGeneratedValue(sequenceName = "product_sequence", allocationSize = 1)
 *     private Long id;
 *
 *     private String name;
 *     // Constructors, getters, setters, other fields, etc.
 * }
 * }</pre>
 * </p>
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface SequenceGeneratedValue {

  /**
   * The name of the sequence in the database
   */
  String sequenceName();

  /**
   * The value to increment the sequence by
   */
  int allocationSize() default 1;

}
