version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bibernate_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
      - ./test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
